name: volcsarvatory
channels:
  - conda-forge
dependencies:
  - python=3.12
  - cartopy
  - fsspec
  - gdal
  - geopandas
  - hyp3_sdk
  - jupyterlab
  - networkx
  - numpy
  - pandas
  - pip
  - plotly
  - pyarrow
  - pygmt
  - pyproj
  - rasterio
  - shapely
  - pip:
    - opensarlab_lib
    - git+https://github.com/insarlab/MintPy.git@4bbca8c # Install from commit until release > 1.6.1
    - git+https://github.com/mfangaritav/Discovery-asf_search.git#egg=asf_search[sbas]
